# Generated by Django 4.2.13 on 2024-05-17 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("summarizer", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="summary",
            name="word_count",
            field=models.IntegerField(),
        ),
    ]
